{
 "title": "Meteostanice",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  Teplota AS \"Teplota\",\n  Vlhkost AS \"Vlhkost\",\n  Tlak AS \"Tlak\",\n  CO2 AS \"CO2\"\nFROM teplota\nWHERE\n  $__timeFilter(Cas)\nORDER BY Cas"
    }
   ]
  },
  {
   "title": "Teplota",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  Teplota AS \"Teplota\"\nFROM teplota\nWHERE\n  $__timeFilter(Cas) AND\n  Teplota < 50\nORDER BY Cas"
    }
   ]
  },
  {
   "title": "Vlhkost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  Vlhkost AS \"Vlhkost\"\nFROM teplota\nWHERE\n  $__timeFilter(Cas)\nORDER BY Cas"
    }
   ]
  },
  {
   "title": "Tlak",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "yaxes": [
    { "format": "pressurepa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  Tlak\nFROM teplota\nWHERE\n  $__timeFilter(Cas) AND\n  Tlak > 6000\nORDER BY Cas"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  CO2 AS \"CO2\"\nFROM teplota\nWHERE\n  $__timeFilter(Cas)\nORDER BY Cas"
    }
   ]
  },
  {
   "title": "Dest",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  Dest\nFROM teplota\nWHERE\n  $__timeFilter(Cas)\nORDER BY Cas"
    }
   ]
  },
  {
   "title": "Pohyb",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Cas AS \"time\",\n  Pohyb\nFROM pohyb\nORDER BY Cas"
    }
   ]
  }
 ]
}